Change column names  & change merge to deal with idential input/outpu…
DataTron-io/docker-service pull request #23
Opened 2021-01-15 21:10 UTC by sankalp04

…t files

2021-01-18 15:08 UTC, hpierce1312 approved these changes

2021-01-18 19:55 UTC, dhruvrrp requested changes

2021-01-18 19:55 UTC, dhruvrrp commented on batch_predict.py
> +                predict_df = pd.DataFrame(output, columns=['prediction'])
Actually, can we keep this the way it was earlier. Changing this will break scoring metrics.

2021-01-18 19:55 UTC, dhruvrrp commented on batch_predict.py
> +                predict_df = pd.DataFrame(output, columns=['prediction'])
We can do something similar to this https://github.com/DataTron-io/Spark-ML-Evaluation/blob/a57afa241cc56c97799925e58fe0889287fc41fe/src/jobs/model_batch_evaluation/__init__.py#L34

in the batch_metrics.py file

2021-01-18 19:55 UTC, dhruvrrp commented on batch_predict.py
> +                predict_df = pd.DataFrame(output, columns=['prediction'])
@sankalp04

2021-01-19 00:26 UTC, dhruvrrp approved these changes

2021-01-19 00:28 UTC, merged